import crypto from 'crypto';
import { logger } from '../../config/logger';

const ALGORITHM = 'aes-256-gcm';

export function getEncryptionKey(): Buffer | null {
  const keyBase64 = process.env.ENCRYPTION_KEY;
  if (!keyBase64) {
    logger.warn('⚠️ ENCRYPTION_KEY is not set in environment variables! Encrypted API Keys will not work.');
    return null;
  }
  
  // Try to parse the base64 key
  try {
    const key = Buffer.from(keyBase64, 'base64');
    if (key.length !== 32) {
      logger.warn(`⚠️ ENCRYPTION_KEY must be 32 bytes when decoded (current length: ${key.length}). Encryption will fail.`);
      return null;
    }
    return key;
  } catch (error) {
    logger.warn('⚠️ ENCRYPTION_KEY is not a valid base64 string.');
    return null;
  }
}

/**
 * Encrypts a text using AES-256-GCM.
 * Returns the encrypted string in the format: iv:authTag:encryptedData (all in hex)
 */
export function encrypt(text: string): string {
  const key = getEncryptionKey();
  if (!key) {
    throw new Error('ENCRYPTION_KEY is missing or invalid. Cannot encrypt data.');
  }

  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag().toString('hex');
  
  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts an encrypted text generated by the encrypt function.
 */
export function decrypt(encryptedData: string): string {
  const key = getEncryptionKey();
  if (!key) {
    throw new Error('ENCRYPTION_KEY is missing or invalid. Cannot decrypt data.');
  }

  try {
    const parts = encryptedData.split(':');
    if (parts.length !== 3) {
      throw new Error('Invalid encrypted data format');
    }

    const iv = Buffer.from(parts[0], 'hex');
    const authTag = Buffer.from(parts[1], 'hex');
    const encryptedText = parts[2];

    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error: any) {
    throw new Error(`Decryption failed: ${error.message}`);
  }
}
